//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_MAIN                        101
#define IDD_MAINVIEW                    103
#define IDD_CAPTCHA                     104
#define IDD_RESULT                      106
#define IDR_MENU1                       109
#define IDD_IMPORT                      110
#define IDD_ADDID                       111
#define IDD_DELETEID                    112
#define IDB_BITMAP1                     112
#define IDD_DELETE                      113
#define IDI_ICON1                       115
#define IDB_BITMAP2                     120
#define IDB_BITMAP3                     121
#define IDB_BITMAP4                     124
#define IDB_BITMAP5                     125
#define IDB_BITMAP6                     126
#define IDB_BITMAP7                     127
#define IDB_BITMAP8                     128
#define IDD_KNOWLEDGEPOINT              129
#define IDD_HOMEWORK                    130
#define IDD_CHANGEPASSWORD              131
#define IDD_PERSONINFORMATION           132
#define IDD_ABOUT                       133
#define IDD_IMPORTSCORE                 134
#define IDD_IMPORTTEACHER               135
#define IDD_ADDURL                      136
#define IDD_AI                          137
#define IDD_TEXT                        138
#define IDD_NEWS                        139
#define IDD_MUSIC                       140
#define IDI_ICON2                       140
#define IDD_IMPORTSTUDENT               141
#define IDI_ICON3                       144
#define IDC_OK                          1000
#define IDC_LOGIN                       1000
#define IDC_USRENAME                    1004
#define IDC_PASSWORD                    1005
#define IDC_LOGINUSERNAME               1006
#define IDC_LOGINPASSWORD               1007
#define IDC_BUTTON_RESULT               1009
#define IDC_BUTTON_DIANMING             1010
#define IDC_COMBO_course                1013
#define IDC_CAPTCHA                     1016
#define IDC_RESULT                      1023
#define IDC_INFORMATION                 1024
#define IDC_LOGININFORMTION             1025
#define IDC_CLASSNAME                   1028
#define IDC_CLASSNAME2                  1029
#define IDC_CLASSID                     1029
#define IDC_EDIT1                       1035
#define IDC_DELETESTUDENTID             1035
#define IDC_EDITKNOWLEDGEPOINT          1035
#define IDC_EDITOLD                     1035
#define IDC_KEYWORD                     1035
#define IDC_BUTTON1                     1036
#define IDC_BUTTON_DELETE               1036
#define IDC_BUTTONKNOWLEDGEPOINT        1036
#define IDC_EDITNEW                     1036
#define IDC_truncate                    1036
#define IDC_BUTTON_TEXT                 1036
#define IDC_TITLE                       1036
#define IDC_BUTTONMUSIC                 1036
#define IDC_PROGRESS1                   1037
#define IDC_PROGRESSIMPORT              1037
#define IDC_EDITNEWAGAIN                1037
#define IDC_BUTTON_NEWS                 1037
#define IDC_PICURL                      1037
#define IDC_BUTTON2                     1038
#define IDC_BUTTON_IMPORT               1038
#define IDC_EDITQQ                      1038
#define IDC_BUTTON_MUSIC                1038
#define IDC_URL                         1038
#define IDC_COMBO1                      1039
#define IDC_COMBODELETE                 1039
#define IDC_COMBOKNOWLEDGEPOINT         1039
#define IDC_EDITEVERYDAY                1040
#define IDC_BPICTURE                    1041
#define IDC_EDIT2                       1042
#define IDC_EDIT_RESULT                 1042
#define IDC_CONTENT                     1042
#define IDC_MUSICURL                    1042
#define IDC_COMBOCOURSE                 1044
#define IDC_BUTTON_IMPORTFILE           1045
#define IDC_EDIT_FILENAME               1046
#define IDC_COMBOADD                    1047
#define IDC_BUTTON_ADD                  1048
#define IDC_ADDSTUDENTID                1049
#define IDC_COMBO_DEL                   1050
#define IDC_BUTTON_DEL                  1051
#define IDC_STATIC_ActualTotalNumber    1052
#define IDC_STATIC_ActualToNumber       1053
#define IDC_STATIC_NotTotheNumberOf     1054
#define IDC_COMBOHOME                   1056
#define IDC_BUTTONHOME                  1058
#define IDC_EDITHOMEWORK                1059
#define ID_OKPERSON                     1061
#define ID_OKPASSWORD                   1062
#define IDC_EDITNAME                    1063
#define IDC_EDITPHONE                   1064
#define IDC_EDITWECHAT                  1065
#define IDC_BUTTONNEWS                  1067
#define IDC_BUTTONTEXT                  1068
#define IDC_DESCRIPTION                 1069
#define ID_MENUITEM40005                40005
#define ID_MENUITEM_HOMEWORK            40005
#define ID_MENUITEM40007                40007
#define ID_MENUITEMWEIXINWORK           40007
#define ID_MENUITEM40008                40008
#define ID_MENUITEMHELP                 40008
#define ID_MENUITEM40009                40009
#define ID_MENUITEMABOUT                40009
#define ID_MENUITEM40013                40013
#define ID_MENUITEMPASSWORD             40013
#define ID_MENUITEM40014                40014
#define ID_MENUITEMPERSONINFORMATION    40014
#define ID_MENUITEMIMPORT222            40016
#define ID_MENUITEMIMPORT_KNOWLEDGEPOINT 40016
#define ID_MENUITEMDELETEID             40017
#define ID_MENUITEMADDID                40018
#define ID_MENUITEMIMPORT               40019
#define ID_MENUITE_DELETE               40020
#define ID_MENUITEMIMPORTSCORE          40021
#define ID_MENUITEMIMPORTTEACHER        40022
#define ID_MENUITEMIMPORT_URL           40024
#define ID_MENUITEMIMPORTSTUDENT        40026
#define ID_MENUITEMAI                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40027
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
